### ISSUE TITLE
TシャツサイズをCSVに入れる

### ISSUE THREAD

**Issue by fumikito** [wct2019/TicketImporter#2]
Tシャツサイズを表示したいらしいので、CSVをインポートする時にそちらも入れてください。
時間的に厳しそうならこちらで巻き取ります。

**Comment by ryu-compin** [comment]
コードに追加しました、が、、今手元の環境がWindowsでデータの反映がうまく動かないので、今夜データ反映します。

**Comment by ryu-compin** [comment]
項目名はTシャツサイズ："tshirtsize" としています。

**Comment by fumikito** [comment]
@ryu-compin エラーがおきました。

```bash
# Json と CSVが正しい位置に置かれていることは確認済み。
node index.js 

Failed Error: Value for argument "documentPath" is not a valid resource path. Path must be a non-empty string.
    at Object.validateResourcePath (/Users/me/Documents/GitHub/TicketImporter/node_modules/@google-cloud/firestore/build/src/path.js:407:15)
    at CollectionReference.doc (/Users/me/Documents/GitHub/TicketImporter/node_modules/@google-cloud/firestore/build/src/reference.js:1740:20)
    at /Users/me/Documents/GitHub/TicketImporter/index.js:42:50
    at Array.forEach (<anonymous>)
    at transaction.get.then.doc (/Users/me/Documents/GitHub/TicketImporter/index.js:38:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by fumikito** [comment]
データを小分けにするとなんとかなる。
